var carouselData = [
  {
      "_id": "5ff4b74ca7336a5d2e5150a1",
      "id": 1,
      "name": "Private Guesthouse · 2 beds",
      "description": "One of a kind experience",
      "avgRating": 3.75,
      "numratings": 130,
      "image": "https://ddpgithubprojects.s3-us-west-2.amazonaws.com/airbnbs/airbnb2.jpg",
      "rate": 623,
      "wasLiked": false,
      "postedDate": "07/22/2020",
      "longitude": -111.73583,
      "latitude": 21.81694,
      "category": "House",
      "superHost": false,
      "relatedPlaces": [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12
      ],
      "related_place": [
          {
              "_id": "5ff4b74ca7336a5d2e5150a1",
              "id": 1,
              "name": "Private Guesthouse · 2 beds",
              "description": "One of a kind experience",
              "avgRating": 3.75,
              "numratings": 130,
              "image": "https://ddpgithubprojects.s3-us-west-2.amazonaws.com/airbnbs/airbnb2.jpg",
              "rate": 623,
              "wasLiked": false,
              "postedDate": "07/22/2020",
              "longitude": -111.73583,
              "latitude": 21.81694,
              "category": "House",
              "superHost": false,
              "relatedPlaces": [
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10,
                  11,
                  12
              ]
          },
          {
              "_id": "5ff4b74ca7336a5d2e5150a2",
              "id": 2,
              "name": "Royal Bungalow",
              "description": "Once in a lifetime adventure",
              "avgRating": 4.78,
              "numratings": 255,
              "image": "https://ddpgithubprojects.s3-us-west-2.amazonaws.com/airbnbs/airbnb3.jpg",
              "rate": 89,
              "wasLiked": true,
              "postedDate": "05/16/2020",
              "longitude": -91.75243,
              "latitude": 43.82294,
              "category": "Duplex",
              "superHost": true,
              "relatedPlaces": [
                  11,
                  6,
                  3,
                  2,
                  14,
                  11,
                  4,
                  15,
                  7,
                  18,
                  11,
                  9
              ]
          },
          {
              "_id": "5ff4b74ca7336a5d2e5150a3",
              "id": 3,
              "name": "Entire Mansion 5 beds",
              "description": "Cliff Town Retreat",
              "avgRating": 3.25,
              "numratings": 42,
              "image": "https://ddpgithubprojects.s3-us-west-2.amazonaws.com/airbnbs/airbnb4.jpg",
              "rate": 123,
              "wasLiked": false,
              "postedDate": "01/34/2020",
              "longitude": -74.78293,
              "latitude": 53.23648,
              "category": "Mansion",
              "superHost": false,
              "relatedPlaces": [
                  11,
                  6,
                  3,
                  2,
                  14,
                  11,
                  4,
                  15,
                  7,
                  18,
                  11,
                  9
              ]
          },
          {
              "_id": "5ff4b74ca7336a5d2e5150a4",
              "id": 4,
              "name": "Guest Bedroom · 1 bed",
              "description": "Villa by the Sea",
              "avgRating": 4.93,
              "numratings": 85,
              "image": "https://ddpgithubprojects.s3-us-west-2.amazonaws.com/airbnbs/airbnb5.jpg",
              "rate": 342,
              "wasLiked": true,
              "postedDate": "08/13/2020",
              "longitude": -131.71143,
              "latitude": 39.87797,
              "category": "Boat",
              "superHost": true,
              "relatedPlaces": [
                  11,
                  6,
                  3,
                  2,
                  14,
                  11,
                  4,
                  15,
                  7,
                  18,
                  11,
                  9
              ]
          },
          {
              "_id": "5ff4b74ca7336a5d2e5150a5",
              "id": 5,
              "name": "Entire House · 6 beds",
              "description": "Getaway in Paradise",
              "avgRating": 4.23,
              "numratings": 352,
              "image": "https://ddpgithubprojects.s3-us-west-2.amazonaws.com/airbnbs/airbnb6.jpg",
              "rate": 122,
              "wasLiked": false,
              "postedDate": "07/22/2020",
              "longitude": -77.73343,
              "latitude": 64.85694,
              "category": "Castle",
              "superHost": false,
              "relatedPlaces": [
                  11,
                  6,
                  3,
                  2,
                  14,
                  11,
                  4,
                  15,
                  7,
                  18,
                  11,
                  9
              ]
          },
          {
              "_id": "5ff4b74ca7336a5d2e5150a6",
              "id": 6,
              "name": "Entire Residence · 4 beds",
              "description": "One of a kind experience",
              "avgRating": 4.11,
              "numratings": 51,
              "image": "https://ddpgithubprojects.s3-us-west-2.amazonaws.com/airbnbs/airbnb7.jpg",
              "rate": 456,
              "wasLiked": true,
              "postedDate": "05/16/2020",
              "longitude": -68.01197,
              "latitude": 19.50139,
              "category": "Tiny House",
              "superHost": true,
              "relatedPlaces": [
                  11,
                  6,
                  3,
                  2,
                  14,
                  11,
                  4,
                  15,
                  7,
                  18,
                  11,
                  9
              ]
          },
          {
              "_id": "5ff4b74ca7336a5d2e5150a7",
              "id": 7,
              "name": "Private Guesthouse · 2 beds",
              "description": "Once in a lifetime adventure",
              "avgRating": 4.42,
              "numratings": 130,
              "image": "https://ddpgithubprojects.s3-us-west-2.amazonaws.com/airbnbs/airbnb8.jpg",
              "rate": 324,
              "wasLiked": false,
              "postedDate": "01/34/2020",
              "longitude": -161.75583,
              "latitude": 21.81694,
              "category": "Tree House",
              "superHost": false,
              "relatedPlaces": [
                  11,
                  6,
                  3,
                  2,
                  14,
                  11,
                  4,
                  15,
                  7,
                  18,
                  11,
                  9
              ]
          },
          {
              "_id": "5ff4b74ca7336a5d2e5150a8",
              "id": 8,
              "name": "Royal Bungalow",
              "description": "Cliff Town Retreat",
              "avgRating": 4.53,
              "numratings": 255,
              "image": "https://ddpgithubprojects.s3-us-west-2.amazonaws.com/airbnbs/airbnb9.jpg",
              "rate": 144,
              "wasLiked": true,
              "postedDate": "08/13/2020",
              "longitude": -111.73583,
              "latitude": 43.82294,
              "category": "House",
              "superHost": true,
              "relatedPlaces": [
                  11,
                  6,
                  3,
                  2,
                  14,
                  11,
                  4,
                  15,
                  7,
                  18,
                  11,
                  9
              ]
          },
          {
              "_id": "5ff4b74ca7336a5d2e5150a9",
              "id": 9,
              "name": "Entire Mansion 5 beds",
              "description": "Villa by the Sea",
              "avgRating": 3.75,
              "numratings": 42,
              "image": "https://ddpgithubprojects.s3-us-west-2.amazonaws.com/airbnbs/airbnb10.jpg",
              "rate": 126,
              "wasLiked": false,
              "postedDate": "07/22/2020",
              "longitude": -91.75243,
              "latitude": 53.23648,
              "category": "Duplex",
              "superHost": false,
              "relatedPlaces": [
                  11,
                  6,
                  3,
                  2,
                  14,
                  11,
                  4,
                  15,
                  7,
                  18,
                  11,
                  9
              ]
          },
          {
              "_id": "5ff4b74ca7336a5d2e5150aa",
              "id": 10,
              "name": "Guest Bedroom · 1 bed",
              "description": "Getaway in Paradise",
              "avgRating": 4.78,
              "numratings": 85,
              "image": "https://ddpgithubprojects.s3-us-west-2.amazonaws.com/airbnbs/airbnb11.jpg",
              "rate": 425,
              "wasLiked": true,
              "postedDate": "05/16/2020",
              "longitude": -74.78293,
              "latitude": 39.87797,
              "category": "Mansion",
              "superHost": true,
              "relatedPlaces": [
                  11,
                  6,
                  3,
                  2,
                  14,
                  11,
                  4,
                  15,
                  7,
                  18,
                  11,
                  9
              ]
          },
          {
              "_id": "5ff4b74ca7336a5d2e5150ab",
              "id": 11,
              "name": "Entire House · 6 beds",
              "description": "One of a kind experience",
              "avgRating": 3.25,
              "numratings": 352,
              "image": "https://ddpgithubprojects.s3-us-west-2.amazonaws.com/airbnbs/airbnb12.jpg",
              "rate": 623,
              "wasLiked": false,
              "postedDate": "01/34/2020",
              "longitude": -131.71143,
              "latitude": 64.85694,
              "category": "Boat",
              "superHost": false,
              "relatedPlaces": [
                  11,
                  6,
                  3,
                  2,
                  14,
                  11,
                  4,
                  15,
                  7,
                  18,
                  11,
                  9
              ]
          },
          {
              "_id": "5ff4b74ca7336a5d2e5150ac",
              "id": 12,
              "name": "Entire Residence · 4 beds",
              "description": "Once in a lifetime adventure",
              "avgRating": 4.93,
              "numratings": 51,
              "image": "https://ddpgithubprojects.s3-us-west-2.amazonaws.com/airbnbs/airbnb1.jpg",
              "rate": 89,
              "wasLiked": true,
              "postedDate": "08/13/2020",
              "longitude": -77.73343,
              "latitude": 19.50139,
              "category": "Castle",
              "superHost": true,
              "relatedPlaces": [
                  11,
                  6,
                  3,
                  2,
                  14,
                  11,
                  4,
                  15,
                  7,
                  18,
                  11,
                  9
              ]
          }
      ]
  }
];

export default carouselData;